blueapi:
  extraEnvVars:
  # For some dodal instruments
    - name: BEAMLINE
      value: t01
    - name: INSTRUMENT
      value: t01
  # Allows non-hostNetwork
  # non-hostNetwork required to run as user with no extra perms
  # see t01-epics-gateways readme
    - name: EPICS_PVA_NAME_SERVERS
      value: t01-epics-gateways:9075
    - name: EPICS_CA_NAME_SERVERS
      value: t01-epics-gateways:9064
    - name: EPICS_PVA_AUTO_ADDR_LIST
      value: "NO"
    - name: EPICS_CA_AUTO_ADDR_LIST
      value: "NO"

  # blueapi config
  worker:
    env:
      # metadata for logging, numtracker, tiled
      metadata:
        instrument: t01
      # load plans and devices
      sources:
        - kind: dodal
          module: dodal.beamlines.t01
        - kind: planFunctions
          module: dodal.plans
        - kind: planFunctions
          module: my_plans.plans
      events:
        broadcast_status_events: false

    # Send bluesky documents to be consumed by NeXus etc.
    stomp:
      # Must use LoadBalancerIP or DNS if hostNetwork: true
      # See `extraEnvVars`
      url: tcp://t01-rabbitmq-daq
      enabled: true

    # Log to graylog.
    # Default address is correct
    logging:
      level: "INFO"
      graylog:
        enabled: true

    oidc:
      # TODO: once NumTracker, tiled are backed by identity.diamond.ac.uk/realms/dls
      # Switch this to the wellknown of that realm
      well_known_url: "https://authn.diamond.ac.uk/realms/master/.well-known/openid-configuration"
      # When switching to identity.diamond.ac.uk, switch to `t01-blueapi`
      client_id: "blueapi-cli"
      logout_redirect_endpoint: "oauth2/sign_out"

    numtracker:
      url: https://numtracker.diamond.ac.uk/graphql

    scratch:
      root: /workspace_git/
      repositories:
        - name: dodal
          remote_url: https://github.com/DiamondLightSource/dodal.git
        - name: my_plans
          remote_url: https://github.com/DiamondLightSource/my_plans.git

  initContainer:
    enabled: true
    # Removes need to mount /dls or /dls_sw
    # No mounts allows us to run as user with no extra perms
    persistentVolume:
      enabled: true

oauth2:
  # TODO: Merge config and alphaConfig when alphaConfig gets these keys
  config:
    existingSecret: "blueapi-secret"
    configFile: |-
      # Speed up login flow
      skip_provider_button = true
      # Allows pre-authenticated requests from other clients
      skip_jwt_bearer_tokens = true
      # Required as authn.diamond.ac.uk does not provide email claim
      email_domains = [ "*" ]
      # Allows GDA/CLI client to fetch authentication information
      skip_auth_routes=[
      "GET=^/config/oidc",
      ]
      # Allows logout to redirect to idp logout
      whitelist_domains=["authn.diamond.ac.uk"]

      # TODO: make these match recommended:
      # cookie_refresh := Access-Token lifespan - 1m
      # cookie_expire := Keycloak client_session_idle
      cookie_refresh="1m"
      cookie_expire="30m"

  # Reverse proxy sits between Ingress and blueapi
  ingress:
    enabled: true
    hosts:
      - t01-blueapi.diamond.ac.uk
    annotations:
      # TODO: may no longer be required?
      # May be required for fastapi docs page?
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    path: /
    # Required for DLS policy
    pathType: Prefix

  alphaConfig:
    enabled: true

    configData:
      upstreamConfig:
        proxyRawPath: true
        upstreams:
          - id: blueapi
            path: /
            uri: http://t01-blueapi

      providers:
        - provider: oidc
          # TODO: switch to identity.diamond.ac.uk
          id: authn.diamond.ac.uk
          clientID: ${OAUTH2_PROXY_CLIENT_ID}
          clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
          oidcConfig:
            # TODO: switch to identity.diamond.ac.uk
            issuerURL: https://authn.diamond.ac.uk/realms/master

            # authn does not return email claim, identity may also not
            insecureAllowUnverifiedEmail: true
            emailClaim: sub

            # TODO: Add `blueapi` as extra claim to all GUIs
            extraAudiences: ["blueapi"]

      # Pass token into call, for blueapi to check and pass to numtracker, tiled
      injectRequestHeaders:
        - name: Authorization
          values:
            - claim: access_token
              prefix: "Bearer "
