apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blueapi-secret
  namespace: t01-beamline
spec:
  encryptedData:
    # See readme
    client-secret: 
    cookie-secret: 
    client-id: